### ISSUE TITLE
It would be useful if JSON representation could be created from the flat representation

### ISSUE THREAD

**Issue by mojochao** [soheilpro/catj#3]
Handy tool.  What do you think about adding the ability to output the JSON representation when given the flat  representation?

**Comment by zmarouf** [comment]
See -> https://news.ycombinator.com/item?id=20246727

**Comment by soheilpro** [comment]
That's a nice idea but I intend to keep this project for displaying JSON files only.

I think you can use [gron](https://github.com/TomNomNom/gron) for that use case.
